global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: job-queue
    static_configs:
      - targets:
          - bull-exporter:9538
